Gun
State
State Gun.state
Referenced by Fire, PlayerShooter.OnAnimatorIK, OnEnable, Reload, ReloadRoutine, Shot.
PlayerShooter Gun.gunHolder
Referenced by Setup.
LineRenderer Gun.bulletLineRenderer
Referenced by Awake.
AudioSource Gun.gunAudioPlayer
Referenced by Awake.
float Gun.currentSpread
Referenced by Fire, OnEnable, Update.
float Gun.currentSpreadVelocity
Referenced by Update.
float Gun.lastFireTime
Referenced by Fire, OnEnable.
LayerMask Gun.excludeTarget
Referenced by Setup, Shot.
AudioClip Gun.shotClip
Referenced by ShotEffect.
AudioClip Gun.reloadClip
Referenced by ReloadRoutine.
ParticleSystem Gun.muzzleFlashEffect
ParticleSystem Gun.shellEjectEffect
Transform Gun.fireTransform
Referenced by Fire, PlayerShooter.UpdateAimTarget.
Transform Gun.leftHandMount
float Gun.damage
Referenced by Shot.
float Gun.fireDistance
Referenced by Shot, PlayerShooter.UpdateAimTarget.
int Gun.ammoRemain
Referenced by ReloadRoutine.
int Gun.magAmmo
Referenced by OnEnable, ReloadRoutine, Shot.
int Gun.magCapacity
Referenced by OnEnable, Reload, ReloadRoutine.
float Gun.timeBetFire
Referenced by Fire.
float Gun.reloadTime
Referenced by ReloadRoutine.
float Gun.maxSpread
Referenced by Update.
float Gun.stability
Referenced by Fire.
float Gun.restoreFromRecoilSpeed
Referenced by Update.
void Gun.Awake()
References bulletLineRenderer, gunAudioPlayer.
void Gun.OnEnable()
References currentSpread, lastFireTime, magAmmo, magCapacity, state.
void Gun.OnDisable()
void Gun.Shot(Vector3 startPoint, Vector3 direction)
References damage, excludeTarget, fireDistance, magAmmo, ShotEffect, state.
Referenced by Fire.
IEnumerator Gun.ShotEffect(Vector3 hitPosition)
References shotClip.
Referenced by Shot.
IEnumerator Gun.ReloadRoutine()
References ammoRemain, magAmmo, magCapacity, reloadClip, reloadTime, state.
Referenced by Reload.
void Gun.Update()
References currentSpread, currentSpreadVelocity, maxSpread, restoreFromRecoilSpeed.
void Gun.Setup(PlayerShooter gunHolder)
References excludeTarget, gunHolder.
bool Gun.Fire(Vector3 aimTarget)
References currentSpread, fireTransform, lastFireTime, Shot, stability, state, timeBetFire.
Referenced by PlayerShooter.Shoot.
bool Gun.Reload()
References magCapacity, ReloadRoutine, state.
Referenced by PlayerShooter.Reload.