Enemy
State
State Enemy.state
Referenced by BeginAttack, DisableAttack, EnableAttack, FixedUpdate, Update, UpdatePath.
NavMeshAgent Enemy.agent
Referenced by Awake, UpdatePath.
Animator Enemy.animator
Referenced by Awake.
AudioSource Enemy.audioPlayer
Referenced by Awake.
Renderer Enemy.skinRenderer
Referenced by Awake.
float Enemy.turnSmoothVelocity
Referenced by FixedUpdate.
float Enemy.attackDistance
Referenced by Awake, Update.
RaycastHit [] Enemy.hits
Referenced by FixedUpdate.
List<LivingEntity> Enemy.lastAttackedTargets
Referenced by FixedUpdate.
bool Enemy.hasTarget
Referenced by DisableAttack, UpdatePath.
Transform Enemy.attackRoot
Transform Enemy.eyeTransform
Referenced by IsTargetOnSight.
AudioClip Enemy.hitClip
Referenced by ApplyDamage.
AudioClip Enemy.deathClip
Referenced by Die.
float Enemy.runSpeed
Referenced by Setup, UpdatePath.
float Enemy.turnSmoothTime
Referenced by FixedUpdate.
float Enemy.damage
Referenced by FixedUpdate, Setup.
float Enemy.attackRadius
Referenced by Awake, FixedUpdate.
float Enemy.fieldOfView
Referenced by IsTargetOnSight.
float Enemy.viewDistance
Referenced by IsTargetOnSight, UpdatePath.
float Enemy.patrolSpeed
Referenced by Awake, Setup, UpdatePath.
LivingEntity Enemy.targetEntity
Referenced by ApplyDamage, UpdatePath.
LayerMask Enemy.whatIsTarget
Referenced by FixedUpdate, IsTargetOnSight, UpdatePath.
void Enemy.Awake()
References agent, animator, attackDistance, attackRadius, audioPlayer, patrolSpeed, skinRenderer.
void Enemy.Start()
References UpdatePath.
void Enemy.Update()
References attackDistance, BeginAttack, LivingEntity.dead, state.
void Enemy.FixedUpdate()
References attackRadius, damage, LivingEntity.dead, hits, lastAttackedTargets, state, turnSmoothTime, turnSmoothVelocity, whatIsTarget.
IEnumerator Enemy.UpdatePath()
References agent, LivingEntity.dead, hasTarget, IsTargetOnSight, patrolSpeed, runSpeed, state, targetEntity, viewDistance, whatIsTarget.
Referenced by Start.
bool Enemy.IsTargetOnSight(Transform target)
References eyeTransform, fieldOfView, viewDistance, whatIsTarget.
Referenced by UpdatePath.
void Enemy.Setup(float health, float damage, float runSpeed, float patrolSpeed, Color skinColor)
References damage, LivingEntity.health, patrolSpeed, runSpeed.
override bool Enemy.ApplyDamage(DamageMessage damageMessage)
References hitClip, targetEntity.
void Enemy.BeginAttack()
References state.
Referenced by Update.
void Enemy.EnableAttack()
References state.
void Enemy.DisableAttack()
References hasTarget, state.
override void Enemy.Die()
References deathClip.