EnemySpawner
readonly List<Enemy> EnemySpawner.enemies
Referenced by CreateEnemy, Update.
int EnemySpawner.wave
Referenced by SpawnWave, UpdateUI.
float EnemySpawner.damageMax
Referenced by CreateEnemy.
float EnemySpawner.damageMin
Referenced by CreateEnemy.
Enemy EnemySpawner.enemyPrefab
Referenced by CreateEnemy.
float EnemySpawner.healthMax
Referenced by CreateEnemy.
float EnemySpawner.healthMin
Referenced by CreateEnemy.
Transform [] EnemySpawner.spawnPoints
Referenced by CreateEnemy.
float EnemySpawner.speedMax
float EnemySpawner.speedMin
Referenced by CreateEnemy.
Color EnemySpawner.strongEnemyColor
Referenced by CreateEnemy.
void EnemySpawner.Update()
References enemies, GameManager.Instance, GameManager.isGameover, SpawnWave, UpdateUI.
void EnemySpawner.UpdateUI()
References wave.
Referenced by Update.
void EnemySpawner.SpawnWave()
References CreateEnemy, wave.
Referenced by Update.
void EnemySpawner.CreateEnemy(float intensity)
References GameManager.AddScore, damageMax, damageMin, enemies, enemyPrefab, healthMax, healthMin, GameManager.Instance, spawnPoints, speedMin, strongEnemyColor.
Referenced by SpawnWave.