PlayerMovement
CharacterController PlayerMovement.characterController
Referenced by Jump, Move, Start.
PlayerInput PlayerMovement.playerInput
Referenced by FixedUpdate, Start, Update.
PlayerShooter PlayerMovement.playerShooter
Referenced by FixedUpdate, Start.
Animator PlayerMovement.animator
Referenced by Start.
Camera PlayerMovement.followCam
Referenced by Start.
float PlayerMovement.speedSmoothVelocity
Referenced by Move.
float PlayerMovement.turnSmoothVelocity
Referenced by Rotate.
float PlayerMovement.currentVelocityY
Referenced by Jump, Move.
float PlayerMovement.speed
Referenced by Move, UpdateAnimation.
float PlayerMovement.jumpVelocity
Referenced by Jump.
float PlayerMovement.airControlPercent
Referenced by Move.
float PlayerMovement.speedSmoothTime
Referenced by Move.
float PlayerMovement.turnSmoothTime
Referenced by Rotate.
float PlayerMovement.currentSpeed
Referenced by FixedUpdate, Move, UpdateAnimation.
void PlayerMovement.Start()
References animator, characterController, followCam, playerInput, playerShooter.
void PlayerMovement.FixedUpdate()
References PlayerShooter.aimState, currentSpeed, PlayerInput.fire, PlayerInput.jump, Jump, Move, PlayerInput.moveInput, playerInput, playerShooter, Rotate.
void PlayerMovement.Update()
References PlayerInput.moveInput, playerInput, UpdateAnimation.
void PlayerMovement.UpdateAnimation(Vector2 moveInput)
References currentSpeed, speed.
Referenced by Update.
void PlayerMovement.Move(Vector2 moveInput)
References airControlPercent, characterController, currentSpeed, currentVelocityY, speed, speedSmoothTime, speedSmoothVelocity.
Referenced by FixedUpdate.
void PlayerMovement.Rotate()
References turnSmoothTime, turnSmoothVelocity.
Referenced by FixedUpdate.
void PlayerMovement.Jump()
References characterController, currentVelocityY, jumpVelocity.
Referenced by FixedUpdate.