PlayerHealth
Animator PlayerHealth.animator
Referenced by Awake.
AudioSource PlayerHealth.playerAudioPlayer
Referenced by Awake.
AudioClip PlayerHealth.deathClip
Referenced by Die.
AudioClip PlayerHealth.hitClip
Referenced by ApplyDamage.
void PlayerHealth.Awake()
References animator, playerAudioPlayer.
void PlayerHealth.UpdateUI()
References LivingEntity.dead, LivingEntity.health.
Referenced by ApplyDamage, Die, OnEnable, RestoreHealth.
override void PlayerHealth.OnEnable()
References UpdateUI.
override void PlayerHealth.RestoreHealth(float newHealth)
References UpdateUI.
override bool PlayerHealth.ApplyDamage(DamageMessage damageMessage)
References hitClip, UpdateUI.
override void PlayerHealth.Die()
References deathClip, UpdateUI.