PlayerShooter
AimState
AimState PlayerShooter.aimState
Referenced by PlayerMovement.FixedUpdate, OnDisable, OnEnable, Shoot, Update.
Gun PlayerShooter.gun
Referenced by OnAnimatorIK, Reload, Shoot, UpdateAimTarget, UpdateUI.
LayerMask PlayerShooter.excludeTarget
Referenced by Awake, UpdateAimTarget.
PlayerInput PlayerShooter.playerInput
Referenced by FixedUpdate, Start, Update.
Animator PlayerShooter.playerAnimator
Referenced by Start.
Camera PlayerShooter.playerCamera
Referenced by Start.
float PlayerShooter.waitingTimeForReleaseingAim
Referenced by Update.
float PlayerShooter.lastFireInputTime
Referenced by FixedUpdate, Update.
Vector3 PlayerShooter.aimPoint
Referenced by Shoot, UpdateAimTarget, UpdateUI.
bool PlayerShooter.linedUp
Referenced by Shoot.
bool PlayerShooter.hasEnoughDistance
Referenced by Shoot, UpdateUI.
void PlayerShooter.Awake()
References excludeTarget.
void PlayerShooter.Start()
References playerAnimator, playerCamera, playerInput.
void PlayerShooter.OnEnable()
References aimState.
void PlayerShooter.OnDisable()
References aimState.
void PlayerShooter.FixedUpdate()
References PlayerInput.fire, lastFireInputTime, playerInput, PlayerInput.reload, Reload, Shoot.
void PlayerShooter.Update()
References aimState, PlayerInput.fire, lastFireInputTime, playerInput, UpdateAimTarget, UpdateUI, waitingTimeForReleaseingAim.
void PlayerShooter.UpdateAimTarget()
References aimPoint, excludeTarget, Gun.fireDistance, Gun.fireTransform, gun.
Referenced by Update.
void PlayerShooter.UpdateUI()
References aimPoint, gun, hasEnoughDistance, UIManager.Instance.
Referenced by Update.
void PlayerShooter.OnAnimatorIK(int layerIndex)
References gun, Gun.state.
void PlayerShooter.Shoot()
References aimPoint, aimState, Gun.Fire, gun, hasEnoughDistance, linedUp.
Referenced by FixedUpdate.
void PlayerShooter.Reload()
References gun, Gun.Reload.
Referenced by FixedUpdate.